swagger: '2.0'
info:
  version: 1.0.0
  title: Image Only
  description: '<img src="https://s48646.pcdn.co/wp-content/uploads/2023/06/computer-popup-box-screen-warning-of-a-system-being-hacked-1.jpeg">'
paths:
  /:
    get:
      responses:
        '200':
          description: OK
